
version: 2

models:
  - name: transactions
    description: "A starter dbt model"
    columns:
      - name: transaction_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
